#Number of orders: 2
#Number of shipments: 1
#Scenarios:
#  -Baseline: No
#  -Interruption: No
#Challenges:
#  -Drop parts: No
#  -Sensor blackout: No
#  -Part flipping: No
#  -Faulty parts: Yes
#  -Moving obstacle: Yes (obstructing pick from shelf 11)
#2 arms advantageous: Yes
#Time limit: yes

time_limit: -1

options:
  gazebo_state_logging: true
  insert_models_over_bins: true
  insert_models_over_shelves: true
  belt_population_cycles: 10 #How many objects to spawn in total
  spawn_extra_models: true
  model_type_aliases:
    order_part1: gasket_part_red
    order_part2: gasket_part_green
    order_part3: pulley_part_red

shelf_layout:
  row_1: ['base',0,'base','base'] #shelves: 3, 4, 5
  row_2: ['pipe','base',0,'base']   #shelves: 6, 7, 8
  row_3: ['base',0,'collar','collar'] #shelves: 9, 10, 11

aisle_layout:
  person_1:
    location: -1.57
    start_time: 0.
    move_time: 9.
    wait_time: 7.
  person_2:
    location: 1.57
    start_time: 16.
    move_time: 9.
    wait_time: 7.


orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    shipment_count: 2
    destinations: [agv1,agv2]
    products:
      part_0:
        type: pulley_part_red
        pose:
          xyz: [0.12, 0.2, 0]
          rpy: [0, 0, 0]
      part_1:
        type: gasket_part_green
        pose:
          xyz: [0.0, 0.0, 0]
          rpy: [0, 0, '-pi/4']
      part_2:
        type: gasket_part_red
        pose:
          xyz: [-0.15, 0.2, 0]
          rpy: [0, 0, '-pi/4']



belt_models:
  gasket_part_red:
    10.0: #interval at which the object is spawned on the belt
      pose:
        xyz: [0.0, 4.3, 0.92]
        rpy: [0, 0, 'pi/2']

# models_over_bins:
#   bin3:
#     models:
#       disk_part_red:
#         xyz_start: [0.1, 0.1, 0.0]
#         xyz_end: [0.5, 0.5, 0.0]
#         rpy: [0, 0, 0]
#         num_models_x: 3
#         num_models_y: 3

models_over_bins:
  bin1:
    models:
      pulley_part_red:
        xyz_start: [0.15, 0.15, 0.0]
        xyz_end: [0.45, 0.45, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 2
        num_models_y: 2
  # bin2:
  #   models:
  #     piston_rod_part_blue:
  #       xyz_start: [0.1, 0.1, 0.0]
  #       xyz_end: [0.5, 0.5, 0.0]
  #       rpy: [0, 0, 'pi/4']
  #       num_models_x: 3
  #       num_models_y: 3
  # bin8:
  #   models:
  #     gasket_part_red:
  #       xyz_start: [0.1, 0.1, 0.0]
  #       xyz_end: [0.5, 0.5, 0.0]
  #       rpy: [0, 0, 'pi/4']
  #       num_models_x: 3
  #       num_models_y: 3


models_over_shelves:
  shelf8:
    models:
      gasket_part_green:
        xyz_start: [1, -0.3, 0.0]
        xyz_end: [0., -0.4, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 8
        num_models_y: 1



#Faulty gripper
drops:
  drop_regions:
    shipping_box_0_impeding:
      frame: agv1::kit_tray_1
      min:
        xyz: [-0.3, -0.3, 0.0]
      max:
        xyz: [0.3, 0.3, 0.5]
      destination:
        xyz: [0.2, 0.3, 0.05]
        rpy: [0, 0, 0.2]
      product_type_to_drop: gasket_part_red
    shipping_box_0_impeding:
      frame: agv2::kit_tray_2
      min:
        xyz: [-0.3, -0.3, 0.0]
      max:
        xyz: [0.3, 0.3, 0.5]
      destination:
        xyz: [0.2, 0.3, 0.05]
        rpy: [0, 0, 0.2]
      product_type_to_drop: gasket_part_red

# sensor_blackout:
#   product_count: 4 #sensor blackout triggered after 4th product is placed
#   duration: 50


#Faulty products
faulty_products:
  - gasket_part_red_1
  - gasket_part_red_2
