sensors:


  logical_camera_0: # over bin
    type: logical_camera
    pose:
      xyz: [5, 1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_1: # over bin
    type: logical_camera
    pose:
      xyz: [5, -1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_2: # over bin
    type: logical_camera
    pose:
      xyz: [3.082385, 1.750927, 1.82]
      rpy: [0, 'pi/2', 0]

  logical_camera_3: # over bin
    type: logical_camera
    pose:
      xyz: [3.082385, -1.750927, 1.82]
      rpy: [0, 'pi/2', 0]

  logical_camera_4: # over shelf
    type: logical_camera
    pose:
      xyz: [-12.517082-1.1, 3, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_5: # over shelf
    type: logical_camera
    pose:
      xyz: [-12.517082-2.9, 3, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_6: # over shelf
    type: logical_camera
    pose:
      xyz: [-12.517082-1.1, -3, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_7: # over shelf
    type: logical_camera
    pose:
      xyz: [-12.517082-2.9, -3, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_8: # over shelf
    type: logical_camera
    pose:
      xyz: [-12.517082-1.1, 0, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_9: # over shelf
    type: logical_camera
    pose:
      xyz: [-12.517082-2.9, 0, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_10: # over conveyor belt
    type: logical_camera
    pose:
      xyz: [-0.004795, 0, 1.82]
      rpy: [0, 'pi/2', '0']

  logical_camera_11: # over conveyor belt
    type: logical_camera
    pose:
      xyz: [-0.004795, 3, 1.82]
      rpy: [0, 'pi/2', '0']

  logical_camera_12: # over agv 1
    type: logical_camera
    pose:
      xyz: [0, 7, 1.5]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_13: # over agv 2
    type: logical_camera
    pose:
      xyz: [0, -7, 1.5]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_14: # over shelf
    type: logical_camera
    pose:
      xyz: [3.23, 3.558, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_15: # over shelf
    type: logical_camera
    pose:
      xyz: [4.988, 3.558, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_16: # over shelf
    type: logical_camera
    pose:
      xyz: [3.23, -3.588, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_17: # over shelf
    type: logical_camera
    pose:
      xyz: [4.988, -3.588, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  breakbeam_0: 
    type: break_beam
    pose:
      xyz: [-0.874795, 4.71, 0.879306]
      rpy: [0, 0, 'pi']

  breakbeam_1: 
    type: break_beam
    pose:
      xyz: [-17, 4.71, 0.879306]
      rpy: [0, 0, '0']
  
  breakbeam_2: 
    type: break_beam
    pose:
      xyz: [-0.874795, 1.57, 0.879306]
      rpy: [0, 0, 'pi']

  breakbeam_3: 
    type: break_beam
    pose:
      xyz: [-17, 1.57, 0.879306]
      rpy: [0, 0, '0']

  breakbeam_4: 
    type: break_beam
    pose:
      xyz: [-0.874795, -1.57, 0.879306]
      rpy: [0, 0, 'pi']

  breakbeam_5: 
    type: break_beam
    pose:
      xyz: [-17, -1.57, 0.879306]
      rpy: [0, 0, '0']

  breakbeam_6:
    type: break_beam
    pose:
      xyz: [-0.874795, -4.71, 0.879306]
      rpy: [0, 0, 'pi']

  breakbeam_7:
    type: break_beam
    pose:
      xyz: [-17, -4.71, 0.879306]
      rpy: [0, 0, '0']
